logging:
  level:
    '[cologne.manu]': debug
spring:
  security:
    oauth2:
      client:
        registration:
          github:


            client-id: 79ad3c6050d70b030b68
            client-secret: 0acbd5ed78c8bcbbb121f93498aa7983ab7104ba